"""Prepare CICIDS2017 (real or synthetic) for training and evaluation.

    python -m training.prepare_cicids2017 --source synthetic      # data/synthetic/synthetic_cicids2017.csv
    python -m training.prepare_cicids2017 --source real           # every CSV in data/real/
    python -m training.prepare_cicids2017 --source real --path D:/CICIDS2017/TrafficLabelling

The source only decides *which CSV files are read*; everything after that - header
normalisation, label canonicalisation, timestamp repair, category mapping - is the same
code path. Output (read by train_models.py / evaluate.py):

    data/prepared/flows.pkl        one DataFrame, identifier + feature + label columns
    data/prepared/meta.json        {"data_source": "synthetic" | "real", ...}

Row cleaning (NaN/inf, duplicates) and the column pipeline happen in
engine.preprocess at training time, so they are identical for both sources.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from engine.ingest import read_csv_any_encoding, split_frame, standardise_columns  # noqa: E402
from engine.schema import FEATURE_COLUMNS, ID_COLUMNS  # noqa: E402

SYNTHETIC_CSV = ROOT / "data" / "synthetic" / "synthetic_cicids2017.csv"
REAL_DIR = ROOT / "data" / "real"
PREPARED_DIR = ROOT / "data" / "prepared"
DAY_NAMES = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

SYNTHETIC_BANNER = (
    "\n" + "!" * 78 + "\n"
    "!!  DATA SOURCE = SYNTHETIC.  These flows were generated by\n"
    "!!  training/generate_synthetic_flows.py - they are NOT CICIDS2017. Metrics are a\n"
    "!!  smoke test of the pipeline, not evaluation results.\n"
    + "!" * 78 + "\n"
)


def source_files(source: str, path: Path | None) -> list[Path]:
    if source == "synthetic":
        p = path or SYNTHETIC_CSV
        if p.is_dir():
            return sorted(p.glob("*.csv"))
        if not p.exists():
            sys.exit(f"{p} not found - run: python -m training.generate_synthetic_flows")
        return [p]
    p = path or REAL_DIR
    files = sorted(p.glob("*.csv")) if p.is_dir() else [p]
    files = [f for f in files if f.exists()]
    if not files:
        sys.exit(f"No CICIDS2017 CSV files found in {p}. See README.md -> 'Using the real "
                 f"CICIDS2017 dataset'.")
    return files


def _day_from_filename(name: str) -> str | None:
    m = re.search(r"(Monday|Tuesday|Wednesday|Thursday|Friday)", name, re.I)
    return m.group(1).capitalize() if m else None


def load_file(path: Path) -> pd.DataFrame:
    raw = standardise_columns(read_csv_any_encoding(path))
    batch = split_frame(raw, path.name, float_dtype=np.float32)
    df = pd.concat([batch.ids.drop(columns=["Destination Port"]), batch.features], axis=1)
    if batch.labels is None:
        raise ValueError(f"{path.name}: no 'Label' column - cannot use it for training")
    df["Label"] = batch.labels.to_numpy()
    df["Category"] = batch.categories.to_numpy()
    df["source_file"] = path.name
    df["row_in_file"] = np.arange(len(df), dtype=np.int64)

    # Day + time ordering. MachineLearningCVE files have no Timestamp: fall back to the
    # weekday in the filename and the row order as a time proxy.
    ts = df["captured_at"]
    day_from_name = _day_from_filename(path.name)
    if ts.notna().mean() > 0.95:
        df["Day"] = ts.dt.day_name().fillna(day_from_name or "Unknown")
        df["time_proxy"] = False
    else:
        df["Day"] = day_from_name or "Unknown"
        df["time_proxy"] = True
    print(f"  {path.name}: {batch.rows_read:,} rows read, {batch.rows_dropped_empty:,} blank "
          f"rows dropped, {len(df):,} kept")
    return df


def prepare(source: str, path: Path | None = None, benign_fraction: float = 1.0,
            seed: int = 42, out_dir: Path = PREPARED_DIR) -> tuple[pd.DataFrame, dict]:
    files = source_files(source, path)
    print(f"Preparing source='{source}' from {len(files)} file(s)")
    if source == "synthetic":
        print(SYNTHETIC_BANNER)
    df = pd.concat([load_file(f) for f in files], ignore_index=True)

    if benign_fraction < 1.0:
        benign = df["Category"] == "Benign"
        keep = ~benign | (np.random.default_rng(seed).random(len(df)) < benign_fraction)
        print(f"  benign down-sampled to {benign_fraction:.0%}: {int((~keep).sum()):,} rows removed")
        df = df.loc[keep].reset_index(drop=True)

    order = ["captured_at", "source_file", "row_in_file"]
    df = df.sort_values(order, kind="stable", na_position="last").reset_index(drop=True)

    meta = {
        "data_source": source,
        "files": [f.name for f in files],
        "rows": int(len(df)),
        "label_counts": {k: int(v) for k, v in df["Label"].value_counts().items()},
        "category_counts": {k: int(v) for k, v in df["Category"].value_counts().items()},
        "benign_fraction": benign_fraction,
        "time_proxy_used": bool(df["time_proxy"].any()),
        "prepared_at": datetime.now().isoformat(timespec="seconds"),
    }
    if source == "synthetic":
        meta["warning"] = "SYNTHETIC DATA - metrics computed on it are not real evaluation results."

    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_pickle(out_dir / "flows.pkl")
    (out_dir / "meta.json").write_text(json.dumps(meta, indent=2))
    print(f"Wrote {len(df):,} flows -> {out_dir / 'flows.pkl'}")
    print(df["Category"].value_counts().to_string())
    if source == "synthetic":
        print(SYNTHETIC_BANNER)
    return df, meta


def load_prepared(prepared_dir: Path = PREPARED_DIR) -> tuple[pd.DataFrame, dict]:
    pkl, meta_path = prepared_dir / "flows.pkl", prepared_dir / "meta.json"
    if not pkl.exists():
        sys.exit(f"{pkl} not found - run: python -m training.prepare_cicids2017 --source synthetic")
    meta = json.loads(meta_path.read_text())
    return pd.read_pickle(pkl), meta


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", choices=["synthetic", "real"], required=True)
    ap.add_argument("--path", type=Path, default=None,
                    help="override the input file/directory (default: data/synthetic/... or data/real/)")
    ap.add_argument("--benign-fraction", type=float, default=1.0,
                    help="randomly keep this share of BENIGN rows (e.g. 0.3 on low-RAM machines)")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args(argv)
    prepare(args.source, args.path, args.benign_fraction, args.seed)


# Re-exported for the training scripts.
__all__ = ["prepare", "load_prepared", "FEATURE_COLUMNS", "ID_COLUMNS", "SYNTHETIC_BANNER"]

if __name__ == "__main__":
    main()
